/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Uart.h"
/* Header for class Uart */

#ifndef _Included_Uart
#define _Included_Uart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Uart
 * Method:    openDev
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Uart_openDev
  (JNIEnv * env, jclass cls, jint num)
  {
    return num*num;

  }

/*
 * Class:     Uart
 * Method:    closeDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Uart_closeDev
  (JNIEnv * env, jclass cls)
  {
    return 123;
  }

/*
 * Class:     Uart
 * Method:    writeBuf
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Uart_writeBuf
  (JNIEnv * env, jclass cls, jint fd, jstring str, jint len)
  {
    return 456;
  }

/*
 * Class:     Uart
 * Method:    readBuf
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Uart_readBuf
  (JNIEnv * env, jclass cls, jint fd);
{
  char* str = "hello apk!";
  return (*env)->NewStringUTF(env,str);
}
#ifdef __cplusplus
}
#endif
#endif
