/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Uart */

#ifndef _Included_Uart
#define _Included_Uart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Uart
 * Method:    openDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_anlory_uart_Uart_openDev
  (JNIEnv * env, jclass cls);

/*
 * Class:     Uart
 * Method:    closeDev
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_example_anlory_uart_Uart_closeDev
  (JNIEnv * env, jclass cls);

/*
 * Class:     Uart
 * Method:    writeBuf
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_anlory_uart_Uart_writeBuf
  (JNIEnv * env, jclass cls, jstring str, jint len);

/*
 * Class:     Uart
 * Method:    readBuf
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anlory_uart_Uart_readBuf
  (JNIEnv * env, jclass cls);

#ifdef __cplusplus
}
#endif
#endif
