/* DO NOT EDIT THIS FILE - it is machine generated */
#include "uart_jni.h"
#include <stdio.h>
//#include <jni.h>  /* /usr/lib/jvm/java-1.7.0-openjdk-amd64/include/ */
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include<android/log.h> 
#include <sys/ioctl.h>


/* Header for class Uart */


static int fd = -3;


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Uart
 * Method:    openDev
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_anlory_uart_Uart_openDev
  (JNIEnv * env, jclass cls)
  {
	__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","openDev ");
	fd = open("/dev/ttyHSL1",O_RDWR);
	if(fd < 0){
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","openDev  Error  fd:%d",fd);
		return -1;
	}
    return fd;
  }

/*
 * Class:     Uart
 * Method:    closeDev
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_example_anlory_uart_Uart_closeDev
  (JNIEnv * env, jclass cls)
  {
	__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","Java_com_example_anlory_uart_Uart_closeDev ");
	if(fd >= 0)
		close(fd);
    return 0;
  }

/*
 * Class:     Uart
 * Method:    writeBuf
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_anlory_uart_Uart_writeBuf
  (JNIEnv * env, jclass cls, jstring str, jint len)
  {
	__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","writeBuf ");
	const char * buf = (*env)->GetStringUTFChars(env,str,NULL);
	int ret;
	if(buf == NULL){
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","writeBuf GetStringUTFChars Error");
		return -1;
	}
	ret = write(fd,buf,len);
	if(ret < 0){
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","writeBuf write Error");
		return -1;
	}
	(*env)->ReleaseStringUTFChars(env, str, buf);
    return ret;
  }

/*
 * Class:     Uart
 * Method:    readBuf
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anlory_uart_Uart_readBuf
  (JNIEnv * env, jclass cls)
{
  __android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","Java_com_example_anlory_uart_Uart_readBuf ");
  char str[128] = {0};
  int ret;
  ret = read(fd,str,127);
  if(ret < 0){
	  strcpy(str,"error");
  }
  return (*env)->NewStringUTF(env,str);
}
static JNINativeMethod meMethods[] = {
	{"readBuf","()Ljava/lang/String;",(void *)Java_com_example_anlory_uart_Uart_readBuf},
	{"writeBuf","(Ljava/lang/String;I)I",(void *)Java_com_example_anlory_uart_Uart_writeBuf},
	{"closeDev","()V",(void *)Java_com_example_anlory_uart_Uart_closeDev},
	{"openDev","()I",(void *)Java_com_example_anlory_uart_Uart_openDev},
};

JNIEXPORT jint JNICALL
JNI_OnLoad(JavaVM *jvm, void *reserved)
{
	JNIEnv *env; jclass cls;
	__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","native jni onload ");
	if ((*jvm)->GetEnv(jvm, (void **)&env, JNI_VERSION_1_4)) {
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","GetEnv ");
		return JNI_ERR; /* JNI version not supported */
	}
	cls = (*env)->FindClass(env, "com/jw/uart/Uart");
	if (cls == NULL) {
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","FindClass ");
		return JNI_ERR;
	}
	if((*env)->RegisterNatives(env,cls,meMethods,sizeof(meMethods)/sizeof(meMethods[0])) < 0){
		__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","RegisterNatives ");
		return JNI_ERR;
	}
		
	__android_log_print(ANDROID_LOG_DEBUG,"Uart_Test","native jni onload ");

	return JNI_VERSION_1_4;
}


#ifdef __cplusplus
}
#endif
