/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class led */

#ifndef _Included_led
#define _Included_led
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     led
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_led_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     led
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_led_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     led
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_led_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     led
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_led_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
